ruoyi:
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: ${dou.uploadPath}

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: ${server.port}
spring:
  config:
    import: file:config.properties
  data:
    # redis 配置
    redis:
      # 地址
      host: ${redis.host}
      # 端口，默认为6379
      port: ${redis.port}
      # 数据库索引
      database: ${redis.database}
      # 密码
      password: ${redis.password}
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ${mysql.username}
        password: ${mysql.password}